import React from 'react'
import Sidebar from './Sidebar'
import { Grid } from '@mui/material'
import { Box } from '@mui/system'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import theme from '../src/theme'

type ComponentType = {
  page: React.ReactNode
}

const PageLayout: React.FC<ComponentType> = ({ page }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box sx={{ flexGrow: 1, background: theme.palette.background.default }}>
        <Grid container spacing={0}>
          <Grid
            item
            xs={12}
            md={3}
            lg={2.5}
            sx={{
              width: 300,
              height: '100hv',
              // background: theme.palette.background.paper,
              // borderRight: '1px solid #eaeaea',
            }}
          >
            <Sidebar />
          </Grid>
          <Grid item xs={12} md={9} lg={9.5}>
            {page}
          </Grid>
        </Grid>
      </Box>
    </>
  )
}

export default PageLayout
