import React from 'react'
import Sidebar from './Sidebar/Sidebar'
import { Grid } from '@mui/material'
import { Box } from '@mui/system'
import Head from 'next/head'
import theme from '../src/theme'
import BurgerDrawer from './Sidebar/BurgerDrawer'
import SidebarGrid from './Sidebar/SidebarGrid'

type ComponentType = {
  page: React.ReactNode
}

const PageLayout: React.FC<ComponentType> = ({ page }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        sx={{
          flexGrow: 1,
          background: theme.palette.background.default,
          height: '100vh',
        }}
      >
        <SidebarGrid sidebar={<Sidebar />} page={page} />
      </Box>
    </>
  )
}

export default PageLayout
